site_name: ProfilePress WordPress Plugin
site_url: http://docs.profilepress.net
site_description: Documentation for ProfilePress plugin - The ultimate plugin for creating user account forms such as login, registration, password reset, front-end edit profile forms as well as front-end user profile for WordPress
site_favicon: favicon.ico
theme_dir: 'readthedocs'
repo_url: https://github.com/ProfilePress/documentation/
repo_name: GitHub
site_author: Agbonghama Collins
pages:
- Home: index.md
- Get Started:
    - 'Installation': 'installation.md'
    - 'Uninstall': 'uninstall.md'
    - 'Quick Start': 'quickstart.md'
    - 'Shortcodes Doc': 'shortcode-doc.md'
    - 'Theme Installation': 'install-theme.md'
- Building:
    - 'Login Form': 'build/login-form.md'
    - 'Registration Form': 'build/registration-form.md'
    - 'Password Reset Form': 'build/password-reset.md'
    - 'Edit Profile Form': 'build/edit-profile.md'
    - 'Front-end Profile': 'build/user-profile.md'
    - 'Widgets': 'build/widgets.md'
    - 'Shortcode List': 'build/shortcodes.md'
- Configuration: 
    - 'Redirections': 'configuration/redirections.md'
    - 'Front-end Profile': 'configuration/front-end-profile.md'
    - 'Registration Sugars': 'configuration/registration.md'
    - 'Password Reset': 'configuration/password-reset.md'
    - 'Custom Fields': 'configuration/custom-fields.md'
- Social Login:
    - 'Configuration': 'social-login/configuration.md'
    - 'Creating a Facebook Application': 'social-login/facebook.md'
    - 'Creating a Twitter Application': 'social-login/twitter.md'
    - 'Creating a LinkedIn Application': 'social-login/linkedin.md'
    - 'Creating a Google+ Application': 'social-login/google.md'
    - 'Creating a GitHub Application': 'social-login/github.md'
- Extras:
    - 'reCAPTCHA': 'extras/recaptcha.md'
    - 'Log in With Email': 'extras/email-login.md'
    - 'Global Administrator Password': 'extras/global-admin-password.md'
    - 'User Moderation': 'extras/user-moderation.md'
    - 'One-time Passwordless Login': 'extras/passwordless-login.md'
- Advanced:
    - 'Theme Development': 'advanced/theme-development.md'
- Extensions: 
    - 'MailChimp': 'extensions/mailchimp.md'
    - 'Email Confirmation': 'extensions/email-confirmation.md'