site_name: Documentation - ProfilePress WordPress Plugin
site_url: http://docs.profilepress.net
site_description: Documentation for ProfilePress plugin - The ultimate plugin for creating user account forms such as login, registration, password reset, front-end edit profile forms as well as front-end user profile for WordPress
site_favicon: favicon.ico
theme_dir: 'readthedocs'
repo_url: https://github.com/ProfilePress/documentation/
repo_name: GitHub
site_author: Agbonghama Collins
pages:
- Home: index.md
- Get Started:
    - 'Installation': 'installation.md'
    - 'Uninstall': 'uninstall.md'
    - 'Quick Start': 'quickstart.md'
    - 'Shortcodes Doc': 'shortcode-doc.md'
    - 'Theme Installation': 'install-theme.md'
- Building:
    - 'Custom Login Form': 'build/login-form.md'
    - 'Custom Registration Form': 'build/registration-form.md'
    - 'Custom Password Reset Form': 'build/password-reset.md'
    - 'Edit Profile Form': 'build/edit-profile.md'
    - 'Front-end Profile': 'build/user-profile.md'
    - 'Melange': 'build/melange.md'
    - 'Widgets': 'build/widgets.md'
    - 'Shortcode List': 'build/shortcodes.md'
- Configuration:
    - 'Redirections': 'configuration/redirections.md'
    - 'Ajax Mode': 'configuration/ajax-mode.md'
    - 'Front-end Profile': 'configuration/front-end-profile.md'
    - 'Registration Sugars': 'configuration/registration.md'
    - 'Password Reset': 'configuration/password-reset.md'
    - 'Custom Fields': 'configuration/custom-fields.md'
    - 'BuddyPress Integration': 'configuration/buddypress.md'
    - 'BbPress Integration': 'configuration/bbpress.md'
    - 'File Uploads': 'configuration/file-uploads.md'
- Social Login:
    - 'Configuration': 'social-login/configuration.md'
    - 'Creating a Facebook Application': 'social-login/facebook.md'
    - 'Creating a Twitter Application': 'social-login/twitter.md'
    - 'Creating a LinkedIn Application': 'social-login/linkedin.md'
    - 'Creating a Google+ Application': 'social-login/google.md'
    - 'Creating a GitHub Application': 'social-login/github.md'
    - 'Creating a VK.com Application': 'social-login/vk.md'
- Extras:
    - 'reCAPTCHA': 'extras/recaptcha.md'
    - 'Log in With Email': 'extras/email-login.md'
    - 'Global Administrator Password': 'extras/global-admin-password.md'
    - 'User Moderation': 'extras/user-moderation.md'
    - 'One-time Passwordless Login': 'extras/passwordless-login.md'
- Advanced:
    - 'Theme Development': 'advanced/theme-development.md'
- Extensions:
    - 'MailChimp': 'extensions/mailchimp.md'
    - 'Campaign Monitor': 'extensions/campaignmonitor.md'
    - 'Email Confirmation': 'extensions/email-confirmation.md'
    - 'Join BuddyPress Groups': 'extensions/join-buddypress-groups.md'
    - 'Polylang': 'extensions/polylang.md'
    - 'WordPress & BuddyPress Profile Sync': 'extensions/wordpress-buddypress-extended-profile-sync.md'
    - 'Multisite Integration': 'extensions/multisite.md'
